# Homeserver details.
homeserver:
  # The address that this appservice can use to connect to the homeserver.
  address: https://matrix.org
  # The domain of the homeserver (for MXIDs, etc).
  domain: matrix.org

# Application service host/registration related details.
# Changing these values requires regeneration of the registration.
appservice:
  # The address that the homeserver can use to connect to this appservice.
  address: http://localhost:8080

  # The hostname and port where this appservice should listen.
  hostname: 0.0.0.0
  port: 8080

  # The unique ID of this appservice.
  id: translator
  # Appservice bot details.
  bot:
    # Username of the appservice bot.
    username: translator_bot
    # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
    # to leave display name/avatar as-is.
    displayname: Translator Bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr

  # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
  as_token: "This value is generated when generating the registration"
  hs_token: "This value is generated when generating the registration"

logfile: error.log
